package ServerObjectInterfaceApp;


/**
* ServerObjectInterfaceApp/ServerObjectInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/rafi/distributed-system-final-project/src/ServerObjectInterface.idl
* Sunday, March 24, 2019 3:17:00 o'clock PM EDT
*/

public interface ServerObjectInterfaceOperations 
{
  String addItem (String managerId, String itemID, String itemName, int quantity);
  String listItemAvailability (String managerID);
  String removeItem (String managerID, String itemID, int quantity);
  boolean borrowItem (String userID, String itemID, int numberOfDay);
  String findItem (String userID, String itemName);
  boolean returnItem (String userID, String itemID);
  boolean waitInQueue (String userID, String itemID);
  boolean exchangeItem (String userID, String newItemID, String oldItemID);
  void shutdown ();
} // interface ServerObjectInterfaceOperations
