package ServerObjectInterfaceApp;


/**
* ServerObjectInterfaceApp/ServerObjectInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/rafi/distributed-system-final-project/src/ServerObjectInterface.idl
* Sunday, March 24, 2019 3:17:00 o'clock PM EDT
*/

public interface ServerObjectInterface extends ServerObjectInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ServerObjectInterface
